export const DATABASE_CLIENT = Symbol('DATABASE_CLIENT');
export const ZALO_IDENTITY_PROVIDER = Symbol('ZALO_IDENTITY_PROVIDER');
export const MEDIA_STORAGE_PROVIDER = Symbol('MEDIA_STORAGE_PROVIDER');
