export const WORKER_DATABASE_CLIENT = Symbol('WORKER_DATABASE_CLIENT');
export const OUTBOX_MESSAGE_HANDLERS = Symbol('OUTBOX_MESSAGE_HANDLERS');
export const WORKER_AFTER_SALE_EVIDENCE_SCANNER = Symbol('WORKER_AFTER_SALE_EVIDENCE_SCANNER');
export const WORKER_AFTER_SALE_EVIDENCE_STORAGE = Symbol('WORKER_AFTER_SALE_EVIDENCE_STORAGE');
export const WORKER_PAYMENT_PROVIDER_RESOLVER = Symbol('WORKER_PAYMENT_PROVIDER_RESOLVER');
export const WORKER_PAYMENT_PROVIDER = WORKER_PAYMENT_PROVIDER_RESOLVER;
export const WORKER_SHIPPING_PROVIDER_RESOLVER = Symbol('WORKER_SHIPPING_PROVIDER_RESOLVER');
