export const WORKER_DATABASE_CLIENT = Symbol('WORKER_DATABASE_CLIENT');
export const OUTBOX_MESSAGE_HANDLERS = Symbol('OUTBOX_MESSAGE_HANDLERS');
export const WORKER_PAYMENT_PROVIDER = Symbol('WORKER_PAYMENT_PROVIDER');
