export const WORKER_DATABASE_CLIENT = Symbol('WORKER_DATABASE_CLIENT');
export const OUTBOX_MESSAGE_HANDLERS = Symbol('OUTBOX_MESSAGE_HANDLERS');
export const WORKER_PAYMENT_PROVIDER_RESOLVER = Symbol('WORKER_PAYMENT_PROVIDER_RESOLVER');
export const WORKER_PAYMENT_PROVIDER = WORKER_PAYMENT_PROVIDER_RESOLVER;
